
CREATE TABLE BALANCE (
    ID INT NOT NULL  AUTO_INCREMENT
    , ACTIVE_AMOUNT_VALUE NUMBER NOT NULL
    , ACTIVE_AMOUNT_CURRENCY VARCHAR(5) NOT NULL
    , HOLD_AMOUNT_VALUE NUMBER NOT NULL
    , HOLD_AMOUNT_CURRENCY VARCHAR(5) NOT NULL
    , PRIMARY KEY (ID)
);

CREATE TABLE MERCHANT (
    ID INT NOT NULL  AUTO_INCREMENT
    , NAME VARCHAR(50) NOT NULL
    , FULL_NAME VARCHAR(120) NOT NULL
    , PRIMARY KEY (ID)
);

CREATE TABLE MERCHANT_BALANCE (
    ID INT NOT NULL  AUTO_INCREMENT
    , MERCHANT INT NOT NULL
    , BALANCE INT NOT NULL
    , PRIMARY KEY (ID)
    , CONSTRAINT FK_MERCHANT_BALANCE_1 FOREIGN KEY (MERCHANT) REFERENCES MERCHANT(ID)
    , CONSTRAINT FK_MERCHANT_BALANCE_2 FOREIGN KEY (BALANCE) REFERENCES BALANCE(ID)
);

CREATE TABLE TXN (
    ID INT NOT NULL  AUTO_INCREMENT
    , SOURCE_BALANCE INT NOT NULL
    , DESTINATION_BALANCE INT NOT NULL
    , AMOUNT_VALUE NUMBER NOT NULL
    , AMOUNT_CURRENCY VARCHAR(5) NOT NULL
    , PRIMARY KEY (ID)
    , CONSTRAINT FK_TXN_1 FOREIGN KEY (SOURCE_BALANCE) REFERENCES BALANCE(ID)
    , CONSTRAINT FK_TXN_2 FOREIGN KEY (DESTINATION_BALANCE) REFERENCES BALANCE(ID)
);

CREATE TABLE PAYMENT (
	ID INT NOT NULL  AUTO_INCREMENT
	, MERCHANT INT NOT NULL
  , TRANSACTION INT
  , AMOUNT_VALUE NUMBER NOT NULL
  , AMOUNT_CURRENCY VARCHAR(5) NOT NULL
	, PRIMARY KEY (ID)
  , CONSTRAINT FK_PAYMENT_1 FOREIGN KEY (MERCHANT) REFERENCES MERCHANT(ID) ON DELETE CASCADE
  , CONSTRAINT FK_PAYMENT_2 FOREIGN KEY (TRANSACTION) REFERENCES TXN(ID)
);
