CREATE TABLE BONUS_PROGRAM(
	ID INT NOT NULL
	, DESCRIPTION VARCHAR(512) NOT NULL
	, PERCENT NUMBER NOT NULL
	, CAN_BE_CHANGED INT DEFAULT 0
	, PRIMARY KEY (ID)
);

CREATE TABLE BONUS_PROGRAM_PARTNER(
	ID INT NOT NULL
	, PROGRAM INT NOT NULL
	, PARTNER INT NOT NULL
  , BY_DEFAULT INT DEFAULT 0
	, PRIMARY KEY (ID)
  , CONSTRAINT FK_BONUS_PROGRAM_PARTNER_1 FOREIGN KEY (PROGRAM) REFERENCES BONUS_PROGRAM(ID)  ON DELETE CASCADE
  , CONSTRAINT FK_BONUS_PROGRAM_PARTNER_2 FOREIGN KEY (PARTNER) REFERENCES PARTNER(ID)  ON DELETE CASCADE
);
